spring:
  security:
    oauth2:
      client:
        registration:
          google:
            client-id: 526640857602-8kpfa8vu3nkfd3sf3s2avf64de9dm4ik.apps.googleusercontent.com
            client-secret: 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

  datasource:
    url: jdbc:mysql://127.0.0.1:3306/tasklist
    username: root
    password: 123454
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: update
      show-sql: true
      dialect: org.hibernate.dialect.MySQLDialect





